name: Spring Boot Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: spring-server
      CONTAINER_NAME: spring-server
      DEPLOY_DIR: /home/ubuntu/workspace
      DOCKER_COMPOSE_PATH: /home/ubuntu/workspace/docker-compose.yml

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (no tests)
        run: ./gradlew clean build -x test

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "${{ env.DEPLOY_DIR }}"

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd $DEPLOY_DIR
            docker compose down
            docker compose up -d --build
